name: build-test
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: false
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build GitHub Container Registry
        uses: ./.github/actions/build-images
        with:
          registry: "ghcr.io"
          repository: "${{ github.repository }}"
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
          version: "${{ github.event.inputs.version }}"
          latest: "true"
          push: "false"

      - name: Build Docker Hub
        uses: ./.github/actions/build-images
        with:
          registry: "docker.io"
          repository: "${{ github.repository }}"
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          version: "${{ github.event.inputs.version }}"
          latest: "true"
          push: "false"
