name: build-test
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: false
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache digests
        uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ runner.os }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download latest earthly
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.5.16/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build GitHub Container Registry
        uses: ./.github/actions/build-images
        with:
          registry: "ghcr.io"
          repository: "${{ github.repository }}"
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
          version: "${{ github.event.inputs.version }}"
          latest: "true"
          push: "false"

      - name: Build Docker Hub
        uses: ./.github/actions/build-images
        with:
          registry: "docker.io"
          repository: "${{ github.repository }}"
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          version: "${{ github.event.inputs.version }}"
          latest: "true"
          push: "false"
